# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration
[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,read_customers,read_locations,read_merchant_managed_fulfillment_orders,read_orders,read_third_party_fulfillment_orders,write_products"

[webhooks]
api_version = "2024-10"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
compliance_topics = [
  "customers/data_request",
  "customers/redact",
  "shop/redact",
]
uri = "/webhooks/mandatory"

[pos]
embedded = false