# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration
# You have to create your own shopify.app.development.toml file to serve your development environment and make sure you use it when running shopify app dev (shopify app config use will help you)
client_id = "app-api-key"
name = "app-name"
handle = "app-name"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,read_customers,read_locations,read_merchant_managed_fulfillment_orders,read_orders,read_third_party_fulfillment_orders,write_products"

[auth]
redirect_urls = [
  "https://example.com/auth/callback",
  "https://example.com/auth/shopify/callback",
  "https://example.com/api/auth/callback",
]

[webhooks]
api_version = "2024-10"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
compliance_topics = [
  "customers/data_request",
  "customers/redact",
  "shop/redact",
]
uri = "/webhooks/mandatory"

[pos]
embedded = false